### ISSUE TITLE
Onboarding: Tuan Tran

### ISSUE THREAD

**Issue by jiri-janousek** [tiliado/nuvolaplayer.project#17]
@tuan43 wrote:

> Thanks for your work! I'm also a software developer so I understand the amount of time and effort that went into this project. Let me know if I can help with your project with my time. [...]
> 
> I have skills in Python and JavaScript. I'm pretty sure I can figure out GTK and how to integrate with other libraries as well.

TODO: Figure out how he could help.

@tuan43, if you have any questions, ask here :-)

**Comment by jiri-janousek** [comment]
How about Grab GNOME proxy settings tiliado/tiliado-repositories#4?

**Comment by jiri-janousek** [comment]
@tuan43, if you have some JavaScript skills, how about creating a web app script or two? See
- [List of service request](https://github.com/tiliado/nuvolaplayer/labels/new%20service)
- [Service Integration Developer Documentation](https://tiliado.github.io/nuvolaplayer/development/apps.html)

**Comment by tuan43** [comment]
OK. I'll take a look tonight.

Thanks,
Tuan

On Thu, Nov 19, 2015 at 7:03 AM, Jiří Janoušek < notifications@github.com [notifications@github.com] > wrote:
@tuan43 [https://github.com/tuan43] , if you have some JavaScript skills, how about creating a web app script or
two? See
- List of service request
  [https://github.com/tiliado/nuvolaplayer/labels/new%20service]
- Service Integration Developer Documentation
  [https://tiliado.github.io/nuvolaplayer/development/apps.html]

—
Reply to this email directly or view it on GitHub
[https://github.com/tiliado/nuvolaplayer.project/issues/17#issuecomment-158051959] .[https://github.com/notifications/beacon/AEXCxyeKZ6HdpLV704SzgwyiaCOa01QMks5pHcAvgaJpZM4GZN0n.gif]

**Comment by tuan43** [comment]
Hi Jiri,
Do you happen to have some time to IM?

Thanks,
Tuan

Tuan Tran | tuan43@gmail.com

**Comment by jiri-janousek** [comment]
It is actually pretty difficult to catch me for IM. What would you like to discuss?

**Comment by tuan43** [comment]
Just how to get started really. I've checked out the project, but don't see any
JS files...

Thanks,
Tuan

On Fri, Nov 27, 2015 at 2:53 PM, Jiří Janoušek < notifications@github.com [notifications@github.com] > wrote:
It is actually pretty difficult to catch me for IM. What would you like to
discuss?

—
Reply to this email directly or view it on GitHub
[https://github.com/tiliado/nuvolaplayer.project/issues/17#issuecomment-160202328] .[https://github.com/notifications/beacon/AEXCx0br1P-_IGHNx56fnuJIMtHKx89fks5pKLowgaJpZM4GZN0n.gif]

**Comment by jiri-janousek** [comment]
> Just how to get started really.

The best way to start is to follow [Service Integrations Tutorial](https://tiliado.github.io/nuvolaplayer/development/apps/tutorial.html).

> I've checked out the project, but don't see any JS files...

Have you cloned this repository `tiliado/nuvolaplayer.project`? If so, sorry for the confusion, but this repository is a sort of meta repository for discussions about the project. Actual development occurs in `tiliado/nuvolaplayer` (Nuvola Player core) and `tiliado/nuvola-app-*` (web app scripts) repositories. Is everything clear now?

**Comment by jiri-janousek** [comment]
Hi @tuan43. I'm closing this ticket for now. Feel free to reopen it if you have any questions.
